name: Test 
on: 
  push:
    branches: [ "main" ]

jobs: 
  deploy:
    runs-on: ubuntu-latest 
    steps: 
    - name: Git Clone
      uses: actions/checkout@v4

    - name: Setup Terraform 
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.12.2"
        
    - name: Init
      run: terraform init 
      